// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zrdjmodbefpyvvvgxkss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpyZGptb2RiZWZweXZ2dmd4a3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDE4NDksImV4cCI6MjA2NDUxNzg0OX0.UKJSf8qX1uDb_8QWJgLmKt3f2rbFusibZ6et3hSL-wU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);